version: '3'
services:
    db:
        image: mysql
        ports:
          - "3306:3306"
        volumes:
          - db_data:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=counter_db
          - MYSQL_USER=counter_user
          - MYSQL_PASSWORD=e2c5e7d4129e
          - MYSQL_RANDOM_ROOT_PASSWORD=yes

volumes:
  db_data:
    driver: local
